// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  button: dynamic(() => import('./Button')),
  faqs: dynamic(() => import('./Faqs')),
  form: dynamic(() => import('./Form')),
  image: dynamic(() => import('./Image')),
  logos: dynamic(() => import('./Logos')),
  rich_text: dynamic(() => import('./RichText')),
};
