// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  divider: dynamic(() => import('./Divider')),
  faqs: dynamic(() => import('./Faqs')),
  form: dynamic(() => import('./Form')),
  image: dynamic(() => import('./Image')),
  logos: dynamic(() => import('./Logos')),
  navigation_item: dynamic(() => import('./NavigationItem')),
  rich_text: dynamic(() => import('./RichText')),
  sub_nav: dynamic(() => import('./SubNav')),
};
